### ISSUE TITLE
How to build down+b version

### ISSUE THREAD

**Issue by imaandrew** [CompCom/OptionsMenu#2]
I have a NES Classic Edition which I would like to build options menu for. How do I build the version for the nes classic edition instead of the snes classic edition?

**Comment by CompCom** [comment]
It's built the exact same way you just need to add this [button config](https://github.com/CompCom/OptionsMenu/files/4207797/buttoncfg.zip) to `mod/etc/options_menu/`. Had to zip it as GitHub doesn't allow upload of cfg files so just extract it to that folder. I'll have to edit the makefile to provide an option to build a NES version.

**Comment by CompCom** [comment]
Done. afebd63
