### ISSUE TITLE
Error: cannot access power buttons

### ISSUE THREAD

**Issue by shir00** [CompCom/OptionsMenu#3]
Hi,
when trying to launch the options menu i get an error saying: "cannot access power buttons". I've tried all versions and a complete reset of my NES without any luck. Any ideas why i get this error?

**Comment by CompCom** [comment]
That sounds like the issue fixed in the not officially released version 1.3.2. Try out the latest release and let me know if you still have any issues.

**Comment by impeeza** [comment]
confirm is resolved on 1.3.3

**Comment by shir00** [comment]
As @impeeza says, the issue seems to be resolved on 1.3.3! =)
