### ISSUE TITLE
Not Working on Hakchi 3.7.0

### ISSUE THREAD

**Issue by impeeza** [CompCom/OptionsMenu#5]
Hi, I just Upgraded to Hakchi 2 CE 3.7.0 but when I press L+R the system appears to freeze, the funny part is Hakchi still show the mini as connected and even I can connect using telnet, ftp and sync games.

Other strange thing is what in the Install Module dialog of Hakchi the Options Menu version is 1.2.0  I did download and replace the local copy of file but still recognized as 1.2.0, download the B+Down version and is recognized by Hakchi as 1.3 but also the menu freeze when I try to open it.

**Comment by CompCom** [comment]
That sounds like the issue fixed in the not officially released version 1.3.2. Try out the latest release and let me know if you still have any issues.

**Comment by impeeza** [comment]
Thanks a lot, using version 1.3.3 and so far all works perfectly.  again thanks a lot for your great work.
