### ISSUE TITLE
mod_uninstall binary crashes

### ISSUE THREAD

**Issue by DanTheMan827** [CompCom/OptionsMenu#6]
I know you left the scene CompCom, but if by some stroke of luck you see this, mod_uninstall can't read the power buttons and there's no source available.

**Comment by CompCom** [comment]
I've added the mod uninstall source and it now compiles using the framework of the Options Menu so any framework changes (like power button fixes) are automatically applied to it.

**Comment by DanTheMan827** [comment]
Thanks, and just a question: you wouldn't want to chat on discord, would you?
