### ISSUE TITLE
Hibernate/Standby not working in Hakchi 2 CE 3.8.0

### ISSUE THREAD

**Issue by TechnoFlawgic** [CompCom/OptionsMenu#8]
Installed v1.3.3, menu opens fine however attempting to enter the hibernate/standby menu causes a softlock.

**Comment by CompCom** [comment]
I've added a fix to the hibernate mod in the latest release. If there are any more issues please let me know.

**Comment by TechnoFlawgic** [comment]
Thanks, I'll update today and report back

**Comment by TechnoFlawgic** [comment]
Definitely didn't get around to this until today, tested a few times with no issues. Thanks again.
